package com.starprotect.repository;

import com.starprotect.model.Underwriter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;

@Repository
public class UnderwriterRepository {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private RowMapper<Underwriter> underwriterRowMapper = new RowMapper<Underwriter>() {
        @Override
        public Underwriter mapRow(ResultSet rs, int rowNum) throws SQLException {
            Underwriter uw = new Underwriter();
            uw.setUnderwriterId(rs.getString("underwriter_id"));
            uw.setName(rs.getString("name"));
            uw.setDob(rs.getDate("dob").toLocalDate());
            uw.setJoiningDate(rs.getDate("joining_date").toLocalDate());
            uw.setPassword(rs.getString("password"));
            uw.setCreatedDate(rs.getString("created_date"));
            return uw;
        }
    };

    // Get next Underwriter ID
    public String getNextUnderwriterId() {
        String sql = "SELECT MAX(underwriter_id) FROM underwriter";
        String maxId = jdbcTemplate.queryForObject(sql, String.class);
        if (maxId == null) {
            return "UW101";
        }
        int num = Integer.parseInt(maxId.substring(2));
        return String.format("UW%03d", num + 1);
    }

    // Insert Underwriter - created_date is auto-generated by database
    public int save(Underwriter underwriter) {
        String sql = "INSERT INTO underwriter (underwriter_id, name, dob, joining_date, password) VALUES (?, ?, ?, ?, ?)";
        return jdbcTemplate.update(sql,
            underwriter.getUnderwriterId(),
            underwriter.getName(),
            underwriter.getDob(),
            underwriter.getJoiningDate(),
            underwriter.getPassword()
        );
    }

    // Find by ID
    public Underwriter findById(String underwriterId) {
        String sql = "SELECT * FROM underwriter WHERE underwriter_id = ?";
        try {
            return jdbcTemplate.queryForObject(sql, underwriterRowMapper, underwriterId);
        } catch (Exception e) {
            return null;
        }
    }

    // Find by credentials (for login)
    public Underwriter findByCredentials(String underwriterId, String password) {
        String sql = "SELECT * FROM underwriter WHERE underwriter_id = ? AND password = ?";
        try {
            return jdbcTemplate.queryForObject(sql, underwriterRowMapper, underwriterId, password);
        } catch (Exception e) {
            return null;
        }
    }

    // Update password
    public int updatePassword(String underwriterId, String newPassword) {
        String sql = "UPDATE underwriter SET password = ? WHERE underwriter_id = ?";
        return jdbcTemplate.update(sql, newPassword, underwriterId);
    }

    // Delete by ID - First delete associated policies
    public int deleteById(String underwriterId) {
        String deletePoliciesSql = "DELETE FROM insurance_policy WHERE underwriter_id = ?";
        jdbcTemplate.update(deletePoliciesSql, underwriterId);
        String sql = "DELETE FROM underwriter WHERE underwriter_id = ?";
        return jdbcTemplate.update(sql, underwriterId);
    }

    // Find all underwriters
    public List<Underwriter> findAll() {
        String sql = "SELECT * FROM underwriter ORDER BY underwriter_id";
        return jdbcTemplate.query(sql, underwriterRowMapper);
    }

    // Check if underwriter exists
    public boolean existsById(String underwriterId) {
        String sql = "SELECT COUNT(*) FROM underwriter WHERE underwriter_id = ?";
        Integer count = jdbcTemplate.queryForObject(sql, Integer.class, underwriterId);
        return count != null && count > 0;
    }
}